ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    two_d_mode: true
    publish_tf: true
    publish_velocity: true
    publish_position: true
    publish_acceleration: false

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    odom0: /imars_lite/odom/rtabmap
    odom0_config: [true, true, false,
                  false, false, true,
                  true, true, false,
                  false, false, false,
                  false, false, false]

   
